# generated by terraform, will be overwritten on next terraform run
---
%{ for vol in volumes ~}
volume_linux_device: "${vol.linux_device}"
volume_mount_path: "/var/kunden"
volume_fstype: "${vol.format}"
%{ endfor ~}
